<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Gcg2OfflineServer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Include="resources\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
